package no.nav.familie.ef.sak.brev.dto

enum class FritekstBrevKategori {
    SANKSJON,
    VEDTAK_INVILGELSE,
    VEDTAK_AVSLAG,
    VEDTAK_OPPHØR,
    VEDTAK_REVURDERING,
    VEDTAK_INNVILGELSE_BARNETILSYN,
    VEDTAK_AVSLAG_BARNETILSYN,
    VEDTAK_INNVILGELSE_SKOLEPENGER,
    VEDTAK_AVSLAG_SKOLEPENGER,
    VEDTAK_OPPHØR_BARNETILSYN,
    VEDTAK_OPPHØR_SKOLEPENGER,
    VEDTAK_UTESTENGELSE
}
