package no.nav.familie.ef.sak.brev.dto

enum class FrittståendeBrevKategori {
    INFORMASJONSBREV,
    INNHENTING_AV_OPPLYSNINGER,
    VARSEL_OM_AKTIVITETSPLIKT,
    VARSEL_OM_SANKSJON,
    INNHENTING_AV_KARAKTERUTSKRIFT_HOVEDPERIODE,
    INNHENTING_AV_KARAKTERUTSKRIFT_UTVIDET_PERIODE,
    BREV_OM_SVARTID_KLAGE
}
