version: 2
registries:

updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
    day: "sunday"
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.jetbrains.kotlinx:kotlinx-coroutines-core
    versions:
    - "*-native-mt"
