version: 2
registries:
  maven-repository-maven-pkg-github-com-navikt-fp-felles:
    type: maven-repository
    url: https://maven.pkg.github.com/navikt/fp-felles/
    username: x-access-token
    password: "${{secrets.MAVEN_REPOSITORY_MAVEN_PKG_GITHUB_COM_NAVIKT_FP_FELLES_PASSWORD}}"

updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: no.nav.familie.felles:http-client
    versions:
    - 1.20210416135502_5bf9eff
    - 1.20210419103325_d044927
  - dependency-name: no.nav.familie.felles:util
    versions:
    - 1.20210416135502_5bf9eff
    - 1.20210419103325_d044927
  - dependency-name: no.nav.familie.felles:log
    versions:
    - 1.20210416135502_5bf9eff
    - 1.20210419103325_d044927
  - dependency-name: no.nav.familie.kontrakter:enslig-forsorger-test
    versions:
    - 2.0_20210305131536_dd4cd5d
    - 2.0_20210312160913_1f140c8
    - 2.0_20210416141710_97efcc5
  - dependency-name: no.nav.familie.kontrakter:felles
    versions:
    - 2.0_20210305131536_dd4cd5d
    - 2.0_20210312160913_1f140c8
    - 2.0_20210416141710_97efcc5
  - dependency-name: no.nav.familie.kontrakter:enslig-forsorger
    versions:
    - 2.0_20210305131536_dd4cd5d
    - 2.0_20210312160913_1f140c8
    - 2.0_20210416141710_97efcc5
  - dependency-name: org.springframework.boot:spring-boot-starter-parent
    versions:
    - 2.4.3
    - 2.4.4
    - 2.4.5
  - dependency-name: org.testcontainers:postgresql
    versions:
    - 1.15.3
  - dependency-name: com.github.doyaaaaaken:kotlin-csv-jvm
    versions:
    - 0.15.2
  - dependency-name: no.nav.security:token-validation-test-support
    versions:
    - 1.3.4
    - 1.3.5
  - dependency-name: no.finn.unleash:unleash-client-java
    versions:
    - 4.2.1
  - dependency-name: io.mockk:mockk
    versions:
    - 1.11.0
  - dependency-name: org.jetbrains.kotlin:kotlin-maven-plugin
    versions:
    - 1.4.32
  - dependency-name: org.jetbrains.kotlin:kotlin-maven-allopen
    versions:
    - 1.4.32
  - dependency-name: org.jetbrains.kotlin:kotlin-test-junit5
    versions:
    - 1.4.32
  - dependency-name: org.jetbrains.kotlin:kotlin-stdlib
    versions:
    - 1.4.32
  - dependency-name: no.nav.fpsak.tidsserie:fpsak-tidsserie
    versions:
    - 2.5.6
  - dependency-name: org.jetbrains.kotlinx:kotlinx-coroutines-core
    versions:
    - 1.4.3-native-mt
  registries:
  - maven-repository-maven-pkg-github-com-navikt-fp-felles
