export CREDENTIAL_USERNAME=$(cat $CREDENTIAL_USERNAME_PATH)
export CREDENTIAL_PASSWORD=$(cat $CREDENTIAL_PASSWORD_PATH)
echo "- exported CREDENTIAL_USERNAME og CREDENTIAL_PASSWORD for familie-ef-sak "
