apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ef-sak
  namespace: default
  labels:
    team: teamfamilie

spec:
  image: {{ image }}
  liveness:
    path: /internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  vault:
    enabled: true
    paths:
      - kvPath: /kv/prod/fss/familie-ef-sak/default
        mountPath: /var/run/secrets/nais.io/vault
      - kvPath: /azuread/data/prod/creds/familie-ef-sak
        mountPath: /var/run/secrets/nais.io/azuread
      - kvPath: /serviceuser/data/prod/srvfamilie-ef-sak
        mountPath: /var/run/secrets/nais.io/srvfamilie-ef-sak
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 1024Mi
      cpu: "1"
    requests:
      memory: 512Mi
      cpu: 500m
  secureLogs:
    enabled: true
  ingresses: # Optional. List of ingress URLs that will route HTTP traffic to the application.
    - https://familie-ef-sak.nais.adeo.no
    - https://familie-ef-sak.prod-fss.nais.io
    - https://familie-ef-sak.prod-fss-pub.nais.io
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
    - name: AZURE_CLIENT_ID
      value: /run/secrets/nais.io/azuread/client_id
    - name: AZURE_CLIENT_SECRET
      value: /run/secrets/nais.io/azuread/client_secret
    - name: CREDENTIAL_USERNAME
      value: /run/secrets/nais.io/srvfamilie-ef-sak/username
    - name: CREDENTIAL_PASSWORD
      value: /run/secrets/nais.io/srvfamilie-ef-sak/password
