#######
# Denne er brukt til å gjøre det mulig å bruke tokens lokalt
#
# secret kan hentes fra cluster med "kubectl -n teamfamilie get secret azuread-familie-ef-sak-lokal -o json | jq '.data | map_values(@base64d)'"
#
# Kjøres en gang eller ved endringer med
# kubectl apply -f .deploy/azure-ad-app-lokal.yaml
###
apiVersion: nais.io/v1
kind: AzureAdApplication
metadata:
  name: familie-ef-sak-lokal
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  preAuthorizedApplications:
    - application: familie-ef-sak-frontend-lokal
      cluster: dev-gcp
      namespace: teamfamilie
    - application: familie-prosessering-lokal
      cluster: dev-gcp
      namespace: teamfamilie
    - application: familie-klage-lokal
      cluster: dev-gcp
      namespace: teamfamilie
  tenant: trygdeetaten.no
  secretName: azuread-familie-ef-sak-lokal
  claims:
    groups:
      - id: "01166863-22f1-4e16-9785-d7a05a22df74" # 0000-GA-Enslig-Forsorger-Beslutter
      - id: "ee5e0b5e-454c-4612-b931-1fe363df7c2c" # 0000-GA-Enslig-Forsorger-Saksbehandler
      - id: "19dcbfde-4cdb-4c64-a1ea-ac9802b03339" # 0000-GA-Enslig-Forsorger-Veileder
      - id: "5ef775f2-61f8-4283-bf3d-8d03f428aa14" # 0000-GA-Strengt_Fortrolig_Adresse
      - id: "ea930b6b-9397-44d9-b9e6-f4cf527a632a" # 0000-GA-Fortrolig_Adresse
      - id: "dbe4ad45-320b-4e9a-aaa1-73cca4ee124d" # 0000-GA-Egne_ansatte
      - id: "928636f4-fd0d-4149-978e-a6fb68bb19de" # prosessering.rolle - (0000-GA-STDAPPS)
      - id: "59865891-62a0-4fe3-b282-2e38210d1fbb" # teamfamilie-ef-forvaltning
    extra:
      - "NAVident"
      - "azp_name"
  replyUrls:
    - url: "http://localhost:8030/swagger-ui/oauth2-redirect.html"
  singlePageApplication: true