apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ef-sak
  namespace: teamfamilie
  labels:
    team: teamfamilie

spec:
  image: {{ image }}
  ingresses:
    - {{ingress}}
  liveness:
    path: /internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 1024Mi
      cpu: "1"
    requests:
      memory: 512Mi
      cpu: 500m
  secureLogs:
    enabled: true
  gcp:
    sqlInstances:
      - type: POSTGRES_12 # IF This is changed, all data will be lost. Read on nais.io how to upgrade
        databases:
          - name: familie-ef-sak
            envVarPrefix: DB
            diskAutoresize: true
  accessPolicy:
    inbound:
      rules:
        - application: familie-ef-sak-frontend
        - application: familie-prosessering
        {{#each inboundApplications as |application|}}
        - application: {{application}}
        {{/each}}
        {{#each inboundApplicationsExternal}}
        - application: {{this.application}}
          namespace: {{this.namespace}}
          cluster: {{this.cluster}}
        {{/each}}
    outbound:
      rules:
        - application: familie-brev
        - application: familie-ef-blankett
      external:
        {{#each externalHosts as |host|}}
        - host: {{host}}
        {{/each}}
  azure:
    application:
      enabled: true
      tenant: {{tenant}}
      claims:
        groups:
        {{#each claimGroups as |group|}}
          - id: {{group}}
        {{/each}}
        extra:
          - "NAVident"
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: {{springProfile}}
  envFrom:
    - secret: familie-ef-sak
