apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ef-sak
  namespace: teamfamilie
  labels:
    team: teamfamilie

spec:
  image: {{ image }}
  ingresses:
    - https://familie-ef-sak.intern.dev.nav.no
  liveness:
    path: /internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas:
    min: 2
    max: 2
  tokenx:
    enabled: true
  resources:
    limits:
      memory: 1024Mi
    requests:
      memory: 512Mi
      cpu: 50m
  secureLogs:
    enabled: true
  gcp:
    sqlInstances:
      - type: POSTGRES_14 # IF This is changed, all data will be lost. Read on nais.io how to upgrade
        diskAutoresize: true
        cascadingDelete: false
        highAvailability: false
        pointInTimeRecovery: true
        maintenance:
          day: 7
          hour: 23
        databases:
          - name: familie-ef-sak
            envVarPrefix: DB
  accessPolicy:
    inbound:
      rules:
        - application: familie-ef-sak-frontend
        - application: familie-prosessering
        - application: familie-ef-personhendelse
        - application: familie-prosessering-lokal
        - application: familie-ef-sak-frontend-lokal
        - application: familie-ef-mottak
        - application: familie-ef-soknad-api
        - application: familie-klage
        - application: familie-ef-proxy
          namespace: teamfamilie
          cluster: dev-fss
        - application: familie-ef-proxy-test
          namespace: teamfamilie
          cluster: dev-fss
        - application: familie-ba-sak
        - application: bidrag-grunnlag
          namespace: bidrag
          cluster: dev-gcp
        - application: bidrag-grunnlag-feature
          namespace: bidrag
          cluster: dev-gcp
        - application: tiltakspenger-overgangsstonad
          namespace: tpts
          cluster: dev-gcp
        - application: tilleggsstonader-integrasjoner
          namespace: tilleggsstonader
    outbound:
      rules:
        - application: familie-tilbake
        - application: familie-klage
        - application: familie-brev
        - application: familie-ef-iverksett
        - application: familie-dokument
        - application: familie-ks-sak
        - application: familie-ef-proxy
          cluster: dev-fss
        - application: historisk-pensjon
          namespace: historisk
        - application: veilarbregistrering
          namespace: paw
        - application: skjermede-personer-pip
          namespace: nom
        - application: pdl-fullmakt
          namespace: pdl
          cluster: dev-fss
      external:
        - host: api-gw-q1.oera.no
        - host: familie-oppdrag.dev-fss-pub.nais.io
        - host: familie-integrasjoner.dev-fss-pub.nais.io
        - host: familie-ef-infotrygd.dev-fss-pub.nais.io
        - host: familie-ef-proxy.dev-fss-pub.nais.io
        - host: teamfamilie-unleash-api.nav.cloud.nais.io
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      claims:
        groups:
          - id: "01166863-22f1-4e16-9785-d7a05a22df74" # 0000-GA-Enslig-Forsorger-Beslutter
          - id: "ee5e0b5e-454c-4612-b931-1fe363df7c2c" # 0000-GA-Enslig-Forsorger-Saksbehandler
          - id: "19dcbfde-4cdb-4c64-a1ea-ac9802b03339" # 0000-GA-Enslig-Forsorger-Veileder
          - id: "d21e00a4-969d-4b28-8782-dc818abfae65" # 0000-GA-Barnetrygd # Brukes for å hente perioder til utvidet barnetrygd
          - id: "9449c153-5a1e-44a7-84c6-7cc7a8867233" # 0000-GA-Barnetrygd-Beslutter # Brukes for å hente perioder til utvidet barnetrygd
          - id: "5ef775f2-61f8-4283-bf3d-8d03f428aa14" # 0000-GA-Strengt_Fortrolig_Adresse
          - id: "ea930b6b-9397-44d9-b9e6-f4cf527a632a" # 0000-GA-Fortrolig_Adresse
          - id: "dbe4ad45-320b-4e9a-aaa1-73cca4ee124d" # 0000-GA-Egne_ansatte
          - id: "928636f4-fd0d-4149-978e-a6fb68bb19de" # prosessering.rolle - (0000-GA-STDAPPS)
          - id: "c62e908a-cf20-4ad0-b7b3-3ff6ca4bf38b" # teamfamilie-forvaltning
        extra:
          - "NAVident"
          - "azp_name"
      replyURLs:
        - "https://familie-ef-sak.intern.dev.nav.no/swagger-ui/oauth2-redirect.html"
      singlePageApplication: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev
  envFrom:
    - secret: familie-ef-sak
    - secret: familie-ef-sak-unleash-api-token
  leaderElection: true
  kafka:
    pool: nav-dev