apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ef-sak
  namespace: teamfamilie
  labels:
    team: teamfamilie
  annotations:
    texas.nais.io/enabled: "true"

spec:
  image: {{ image }}
  ingresses:
    - https://familie-ef-sak.intern.nav.no
  liveness:
    path: /internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas:
    min: 2
    max: 4
  tokenx:
    enabled: true
  resources:
    limits:
      memory: 2048Mi
    requests:
      memory: 1024Mi
      cpu: 100m
  secureLogs:
    enabled: true
  gcp:
    sqlInstances:
      - type: POSTGRES_14 # IF This is changed, all data will be lost. Read on nais.io how to upgrade
        tier: db-custom-1-3840
        diskAutoresize: true
        cascadingDelete: false
        highAvailability: true
        pointInTimeRecovery: true
        maintenance:
          day: 7
          hour: 23
        databases:
          - name: familie-ef-sak
            envVarPrefix: DB
        flags:
          - name: "cloudsql.enable_pgaudit"
            value: "on"
          - name: "pgaudit.log"
            value: "write"
  accessPolicy:
    inbound:
      rules:
        - application: familie-ef-sak-frontend
        - application: familie-prosessering
        - application: familie-klage
        - application: familie-ef-personhendelse
        - application: familie-ef-mottak
        - application: familie-ef-soknad-api
        - application: familie-ef-proxy
          namespace: teamfamilie
          cluster: prod-fss
        - application: familie-ba-sak
        - application: bidrag-grunnlag
          namespace: bidrag
          cluster: prod-gcp
        - application: veilarbportefolje
          namespace: obo
          cluster: dev-gcp
        - application: tilleggsstonader-integrasjoner
          namespace: tilleggsstonader
    outbound:
      rules:
        - application: tilbakekreving-backend
          namespace: tilbake
        - application: familie-tilbake
        - application: familie-klage
        - application: familie-brev
        - application: familie-ef-iverksett
        - application: familie-dokument
        - application: familie-ks-sak
        - application: historisk-pensjon
          namespace: historisk
        - application: familie-ef-proxy
          cluster: prod-fss
        - application: paw-arbeidssoekerregisteret-api-oppslag
          namespace: paw
        - application: skjermede-personer-pip
          namespace: nom
        - application: repr-api
          namespace: repr
      external:
        - host: api-gw.oera.no
        - host: familie-oppdrag.prod-fss-pub.nais.io
        - host: familie-integrasjoner.prod-fss-pub.nais.io
        - host: familie-ef-infotrygd.prod-fss-pub.nais.io
        - host: familie-ef-proxy.prod-fss-pub.nais.io
        - host: teamfamilie-unleash-api.nav.cloud.nais.io
  azure:
    application:
      enabled: true
      tenant: nav.no
      claims:
        groups:
          - id: "31778fd8-3b71-4867-8db6-a81235fbe001" # 0000-GA-Enslig-Forsorger-Veileder
          - id: "6406aba2-b930-41d3-a85b-dd13731bc974" # 0000-GA-Enslig-Forsorger-Saksbehandler
          - id: "5fcc0e1d-a4c2-49f0-93dc-27c9fea41e54" # 0000-GA-Enslig-Forsorger-Beslutter
          - id: "87190cf3-b278-457d-8ab7-1a5c55a9edd7" # Group_... teamfamilie - gir tilgang til prosessering
          - id: "847e3d72-9dc1-41c3-80ff-f5d4acdd5d46" # 0000-GA-Barnetrygd # Brukes for å hente perioder til utvidet barnetrygd
          - id: "7a271f87-39fb-468b-a9ee-6cf3c070f548" # 0000-GA-Barnetrygd-Beslutter # Brukes for å hente perioder til utvidet barnetrygd
          - id: "ad7b87a6-9180-467c-affc-20a566b0fec0" # 0000-GA-Strengt_Fortrolig_Adresse
          - id: "9ec6487d-f37a-4aad-a027-cd221c1ac32b" # 0000-GA-Fortrolig_Adresse
          - id: "e750ceb5-b70b-4d94-b4fa-9d22467b786b" # 0000-GA-Egne_ansatte
          - id: "3d718ae5-f25e-47a4-b4b3-084a97604c1d" # teamfamilie-forvaltning
        extra:
          - "NAVident"
          - "azp_name"
      replyURLs:
        - "https://familie-ef-sak.intern.nav.no/swagger-ui/oauth2-redirect.html"
      singlePageApplication: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
  envFrom:
    - secret: familie-ef-sak
    - secret: familie-ef-sak-unleash-api-token
  leaderElection: true
  kafka:
    pool: nav-prod
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
    autoInstrumentation:
      enabled: true
      runtime: java

