ingress: https://familie-ef-sak.intern.nav.no
externalHosts:
  - api-gw.oera.no
  - unleash.adeo.no
  - familie-oppdrag.prod-fss-pub.nais.io
  - familie-ef-infotrygd-feed.prod-fss-pub.nais.io
  - familie-integrasjoner.prod-fss-pub.nais.io
  - infotrygd-enslig-forsoerger.prod-fss-pub.nais.io
springProfile: prod