apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ef-sak
  namespace: teamfamilie
  labels:
    team: teamfamilie

spec:
  image: {{ image }}
  ingresses:
    - https://familie-ef-sak.intern.nav.no
  liveness:
    path: /internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 1024Mi
      cpu: 1500m
    requests:
      memory: 512Mi
      cpu: 500m
  secureLogs:
    enabled: true
  gcp:
    sqlInstances:
      - type: POSTGRES_12 # IF This is changed, all data will be lost. Read on nais.io how to upgrade
        diskAutoresize: true
        cascadingDelete: false
        highAvailability: true
        maintenance:
          day: 7
          hour: 23
        databases:
          - name: familie-ef-sak
            envVarPrefix: DB
  accessPolicy:
    inbound:
      rules:
        - application: familie-ef-sak-frontend
        - application: familie-prosessering
        - application: familie-ef-personhendelse
        - application: familie-ef-mottak
        - application: familie-ef-proxy
          namespace: teamfamilie
          cluster: prod-fss
        - application: familie-ef-mottak
          namespace: teamfamilie
          cluster: prod-fss
        - application: familie-ba-sak
          namespace: teamfamilie
          cluster: prod-gcp
    outbound:
      rules:
        - application: familie-tilbake
        - application: familie-brev
        - application: familie-ef-blankett
        - application: familie-ef-iverksett
        - application: familie-ef-proxy
          cluster: prod-fss
      external:
        - host: api-gw.oera.no
        - host: unleash.nais.io
        - host: familie-oppdrag.prod-fss-pub.nais.io
        - host: familie-integrasjoner.prod-fss-pub.nais.io
        - host: familie-ef-infotrygd.prod-fss-pub.nais.io
        - host: familie-ef-proxy.prod-fss-pub.nais.io
  azure:
    application:
      enabled: true
      tenant: nav.no
      claims:
        groups:
          - id: "31778fd8-3b71-4867-8db6-a81235fbe001" # 0000-GA-Enslig-Forsorger-Veileder
          - id: "6406aba2-b930-41d3-a85b-dd13731bc974" # 0000-GA-Enslig-Forsorger-Saksbehandler
          - id: "5fcc0e1d-a4c2-49f0-93dc-27c9fea41e54" # 0000-GA-Enslig-Forsorger-Beslutter
          - id: "87190cf3-b278-457d-8ab7-1a5c55a9edd7" # Group_87190cf3-b278-457d-8ab7-1a5c55a9edd7 gir tilgang til prosessering
          - id: "847e3d72-9dc1-41c3-80ff-f5d4acdd5d46" # 0000-GA-Barnetrygd # Brukes for å hente perioder til utvidet barnetrygd
          - id: "7a271f87-39fb-468b-a9ee-6cf3c070f548" # 0000-GA-Barnetrygd-Beslutter # Brukes for å hente perioder til utvidet barnetrygd
          - id: "ad7b87a6-9180-467c-affc-20a566b0fec0" # 0000-GA-Strengt_Fortrolig_Adresse
          - id: "9ec6487d-f37a-4aad-a027-cd221c1ac32b" # 0000-GA-Fortrolig_Adresse
        extra:
          - "NAVident"
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
  envFrom:
    - secret: familie
    - secret: familie-ef-sak
