CREATE SEQUENCE BEHANDLING_EKSTERN_ID_SEQ START WITH 1000000 NO CYCLE;
ALTER TABLE behandling ADD COLUMN ekstern_id bigint not null default nextval(BEHANDLING_EKSTERN_ID_SEQ);

CREATE SEQUENCE FAGSAK_EKSTERN_ID_SEQ START WITH 1000000 NO CYCLE;
ALTER TABLE fagsak ADD COLUMN ekstern_id bigint not null default nextval(FAGSAK_EKSTERN_ID_SEQ);