ALTER TABLE behandling ADD COLUMN arsak VARCHAR;
ALTER TABLE behandling ADD COLUMN krav_mottatt TIMESTAMP(3);
UPDATE behandling SET arsak = 'SØKNAD' WHERE type IN ('FØRSTEGANGSBEHANDLING', 'BLANKETT');
UPDATE behandling SET arsak = 'NYE_OPPLYSNINGER' WHERE type IN ('REVURDERING', 'TEKNISK_OPPHØR');
ALTER TABLE behandling ALTER COLUMN arsak SET NOT NULL;